name: Pour People
favicon: null
layout_spectrum: 1
typography_spectrum: 0.607495945179835
title: Pour People
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#983695'
    - '#ffffff'
    - '#414142'
    - '#9f9f9f'
  brandStrength: 0.5
  lightness: 0.6540472840424627
  saturation: 0.3966421619988978
  rhythmicContrast: 0.75
purpose: []
